---
title: 'Homework #3'
author: "Michael Mila"
date: "2/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


2.  List five functions that you could use to get more information about the
mpg dataset.
3. Using the `ggplot2` package create a scatterplot of `hwy` and `cty` and describe the relationship. Why are there so few points visible? Use a geom that helps reduce the amount of overplotting in the scatterplot. (Try ```?geom_jitter```)
4. Apart from the US, most countries use fuel consumption (fuel consumed
over fixed distance) rather than fuel economy (distance traveled with fixed
amount of fuel). How could you convert `cty` and `hwy` into the European
standard of liter/100 km? Introduce corresponding variables into the `mpg` data.
5.  Are cars in 2008 more fuel efficient than cars in 1999? Expand on your answer in (3) for a visual approach to this question. Note: you are not asked to find numeric answers. Instead, interpret plots. 
6. Use the `ggplot2` package to create  side-by-side boxplots of `cty` by `class`. Describe the relationship in 2-3 sentences. 
Change the label for the y-axis to 'city miles per gallon' (see ```?ylab```).  


Note: your submission is supposed to be fully reproducible, i.e. the TA and I will 'knit' your submission in RStudio. 


For the submission: submit your solution in an **R Markdown file** and (just for insurance) submit the **corresponding html (or Word)** file with it. 